            CREATE TABLE IF NOT EXISTS `mri_Qshops` (
              `id` int(11) NOT NULL AUTO_INCREMENT,
                `label` text DEFAULT  NULL,
                `jobname` text DEFAULT  NULL,
                `target` text DEFAULT  NULL,
                `drawmaker` text DEFAULT  NULL,
                `blipcoords` longtext DEFAULT NULL,
                `blipName` text DEFAULT  NULL,
                `blipSprite` longtext DEFAULT NULL,
                `blipCor` longtext DEFAULT NULL,
                `blipscale` longtext DEFAULT NULL,
                `blipEnabled` varchar(255) DEFAULT NULL,
                `MenuCoords` longtext DEFAULT NULL,
                `MenuEnabled` varchar(255) DEFAULT NULL,
                `armazemCoords` longtext DEFAULT NULL,
                `MenuBossEnabled` varchar(255) DEFAULT NULL,
                `shopCoords` longtext DEFAULT NULL,
                `shopsprite` longtext DEFAULT NULL,
                PRIMARY KEY (`id`) USING BTREE,
               UNIQUE KEY `id` (`id`)
            ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;