            CREATE TABLE IF NOT EXISTS `mri_Qshops` (
              `id` int(11) NOT NULL AUTO_INCREMENT,
                `label` text DEFAULT  NULL,
                `jobname` text DEFAULT  NULL,
                `target` text DEFAULT  NULL,
                `drawmaker` text DEFAULT  NULL,
                `blipcoords` longtext DEFAULT NULL,
                `blipname` text DEFAULT  NULL,
                `blipsprite` longtext DEFAULT NULL,
                `blipcolor` longtext DEFAULT NULL,
                `blipscale` longtext DEFAULT NULL,
                `blipenabled` varchar(255) DEFAULT NULL,
                `menucoords` longtext DEFAULT NULL,
                `menuenabled` varchar(255) DEFAULT NULL,
                `storagecoords` longtext DEFAULT NULL,
                `shopcoords` longtext DEFAULT NULL,
                `shopsprite` longtext DEFAULT NULL,
                PRIMARY KEY (`id`) USING BTREE,
               UNIQUE KEY `id` (`id`)
            ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;